site_name: Documentación con mkdocs y GitHub
site_url: https://osalinaseduca.github.io/examen_unidad_6/
docs_dir: 'docs_src'
site_dir: 'docs'
nav:
  - Inicio: inicio.md
  - Guia de instalación Windows 11: Guía_de_instalación_windows.md
  - Especificaciones tecnicas Iphone 16: Especificaciones.md
  - Descargas:
      - Guia de instalación Windows 11 PDF: Guía_de_instalación_windows/Guía_de_instalación_windows.pdf
      - Especificaciones tecnicas Iphone 16 PDF: Especificaciones/Especificaciones.pdf
  
theme:  readthedocs

plugins:
  - search
  - pdf-export:
      enable_if_env: ENABLE_PDF_EXPORT
      media_type: print
